server:
  servlet:
    context-path: /api

spring:
  application:
    name: ddingchun

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:{PORT}/{DB_NAME}
    username: {USERNAME}
    password: {PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true