server:
  servlet:
    context-path: /api

spring:
  application:
    name: ddingchun

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/ddingchun
    username: postgres
    password: 1027
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true